from pathlib import Path
import shutil
import os

from docutils.core import publish_cmdline
from invoke import task
from rellu.tasks import clean
from robot.libdoc import libdoc


assert Path.cwd() == Path(__file__).parent


@task
def kw_docs(ctx):
    """Generates the library keyword documentation

    Documentation is generated by using the Libdoc tool.
    """
    libdoc(str(Path('RequestLibrary.py')),
           str(Path('docs/RequestLibrary.html')))


@task
def project_docs(ctx):
    """Generate project documentation.
     """
    args = ['--stylesheet=style.css,extra.css',
            '--link-stylesheet',
            'docs/index.html']
    publish_cmdline(writer_name='html5', argv=args)
    print(Path(args[-1]).absolute())


@task
def move_docs(ctx):
    """Move report.html and log.html to docs
    """
    log = Path('./log.html')
    report = Path('./report.html')
    dest = Path('.') / 'docs'
    print(log.absolute())
    shutil.copy(log.absolute(), str(dest))
    print(report.absolute())
    shutil.copy(report.absolute(), str(dest))


@task
def remove_docs(ctx):
    """Remove report.html, output.xml and log.html
    """
    log = Path('./log.html')
    report = Path('./report.html')
    output = Path('./output.xml')

    for file_path in [log, report, output]:
        if os.path.exists(file_path):

            print(file_path.absolute())
            os.remove(file_path.absolute())
